### PR TITLE
forward to latest

### PR DESCRIPTION
**Pull request by eile**
Hi John, this is a merge of #345 and current master. Please check if all is to your liking.

### CODE REVIEW

**Comment by biddisco** [comment]
Quite a lot has changed and I have not tested it, so I am not sure yet if all will behave as previously.
The DISABLE_UPDATE option has been removed from docs. Is this because auto updating of repos is not longer done and the user must do so manually instead? I think the docs need improving to explain the correct way of keeping a branch up-to-date or untouched.

It looks like DISABLE_UPDATE has gone, but it still exists in the options list for Git_External. That needs checking.

**Comment by biddisco** [comment]
ok, my bad, I see that targets are now mentioned in the docs. I presume these are never automatically called?

**Comment by eile** [comment]
Correct, rebase is a non-default target.

**Comment by biddisco** [comment]
Is/will there be an option AUTO_UPDATE to say that this repo should always update to branch X, or must we do it manually? I can see a use case for some repos to be updated every time configure is called if the user explicitly wants it.

**Comment by eile** [comment]
Right now you'll have to call 'ninja project-rebase' manually. @rdumusc was quite vocal against auto-updates and managed to convince even me. ;)

**Comment by biddisco** [comment]
Understood. Having auto-update by default was painful, but I may in the future add AUTO_UPDATE as a local option which the user can specifically ask for for on a repo by repo basis. I do that some other time as another PR. 
I will now test this branch and report back.

**Pull request merged**
